install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo test -- --bench
  - rustdoc --test src/lib.rs -L target
  - rustdoc src/lib.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - secure: VNed2UrRM3T8yO9gh2q8NcGwpzngNgeK9lvQ/XGjIiAr0tTzyPP2197snwB+h1fIIvtJRNjYCVgCHIY/JbjlRJ0QvvlARsz4OeVcIkXMnV7GRaxG17k1Vjp0PFUCDF0qpU1ZuxFZbPXYNpHDGXHgwkVQIrTQVsHenRzyWgJvUBk=
